### ISSUE TITLE
**paconn download** fails with InvalidAuthenticationToken error

### ISSUE THREAD

**Issue by dhands5312** [microsoft/PowerPlatformConnectors#2400]
## Issue:
The `paconn download` command fails with and `InvalidAuthenticationToken`

![image](https://user-images.githubusercontent.com/105735128/219750858-6a032183-f434-4837-9096-5357a253f493.png)

## To Reproduce:
- paconn login
  - Go to `https://microsoft.com/devicelogin` and follow the steps to login
- paconn download
  - Select an environment when prompted
- A error is presented stating:
_{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "The received access token has been obtained from wrong audience or resource."
  }
}
401 Client Error: Unauthorized for url: https://api.powerapps.com/providers/Microsoft.PowerApps/apis?api-version=2016-11-01&%24filter=environment%20eq%20%27Default-1bbc4efe-fa71-4e63-abb3-c39e037c688e%27_

## Expected Result:
The paconn download command would present a list of available custom connectors. Once one was selected the custom connector would be downloaded.

## Additional Information
The paconn download command was working earlier this week. I first noticed this failure yesterday afternoon around 3PM EST 2/16/2023.

**Comment by Amjed-Ayoub** [comment]
Dear @dhands5312,

Thank you so much for reaching out.

We are aware of this issue as it is affecting a lot of our partners. Rest assured that we are doing our best to resolve this in a timely manner. 
Please accept our apologies for any inconvenience this may cause.

Thank you so much again for your patience and understanding.

Best regards,
Amjed Ayoub

**Comment by RedsGT** [comment]
@dhands5312, 

Here's temp fix for this issue until the package gets updated.

(For me in Windows 11 this was in "%localappdata%\Programs\Python\Python310\Lib\site-packages\paconn\settings", but YMMV)
1.. Open ...\Lib\site-packages\paconn\settings\settings.py
2. Modify line 57:
Old: "self.resource = resource or 'https://management.core.windows.net/'"
New: "self.resource = resource or 'https://service.powerapps.com/'"
3.  Save it and close out.
4.  Fire up paconn, reauth and you should be good.

**Comment by mamurshe** [comment]
A fix with correct resource id is published in pypi. To update to 0.0.21 run `pip install paconn -U`

This prod version with `0.0.x` version number uses ADAL authentication library and may not work for all cases. A new version with MSAL authentication library, version number 0.1.x, is in development and can be installed from test pypi using `pip install --index-url https://test.pypi.org/simple paconn -U`

**Comment by dhands5312** [comment]
The new paconn version 0.0.21 resolved my connection issue. Thank you!

**Comment by ashes2076** [comment]
I had the same issue today, and @mamurshe thanks for the second method. Now it does work for me. Only thing I wanted to point out that by installing the 0.1.x version i also had to install **msal** package. So  might be helpful for others with the same issue.\

**Comment by SinghAD-coder** [comment]
After following the second option, and then firing `paconn login` results in the below error:

No module named 'msal'
Traceback (most recent call last):
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\knack\invocation.py", line 134, in execute
    self.commands_loader.load_arguments(command)
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\paconn\__main__.py", line 52, in load_arguments
    super(ConnectorsCliCommandsLoader, self).load_arguments(command)
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\knack\commands.py", line 207, in load_arguments
    self.command_table[command].load_arguments()
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\knack\commands.py", line 89, in load_arguments
    cmd_args = self.arguments_loader()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\knack\commands.py", line 242, in arguments_loader
    return list(extract_args_from_signature(CLICommandsLoader._get_op_handler(operation),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\knack\commands.py", line 259, in _get_op_handler
    op = import_module(mod_to_import)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\paconn\commands\login.py", line 10, in <module>
    from paconn.authentication.auth import get_authentication
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\paconn\authentication\auth.py", line 10, in <module>
    from paconn.authentication.msalprofile import MsalProfile
  File "C:\Users\AkashDeepSingh\AppData\Local\Programs\Python\Python311\Lib\site-packages\paconn\authentication\msalprofile.py", line 10, in <module>
    from msal import PublicClientApplication
ModuleNotFoundError: No module named 'msal'
