### ISSUE TITLE
Can't use 'paconn update'

### ISSUE THREAD

**Issue by diegobernardes** [microsoft/PowerPlatformConnectors#289]
**Describe the bug**
`paconn update` never succeeds for me. Running with a debug flag to show that the application spends minutes on this line `urllib3.connectionpool : Starting new HTTPS connection (1): api.powerapps.com:443` before returning with error.

```
urllib3.connectionpool : Starting new HTTPS connection (1): api.powerapps.com:443
urllib3.connectionpool : https://api.powerapps.com:443 "PATCH /providers/Microsoft.PowerApps/apis/abc?api-version=2016-11-01&%24filter=environment%20eq%20%27Default-xyz%27 HTTP/1.1" 502 0
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.7/site-packages/knack/invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.7/site-packages/knack/commands.py", line 131, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/knack/commands.py", line 238, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.7/site-packages/paconn/commands/update.py", line 51, in update
    overwrite_settings=False)
  File "/usr/local/lib/python3.7/site-packages/paconn/operations/upsert.py", line 135, in upsert
    payload=property_definition)
  File "/usr/local/lib/python3.7/site-packages/paconn/apimanager/powerappsrp.py", line 71, in update_connector
    payload=payload)
  File "/usr/local/lib/python3.7/site-packages/paconn/apimanager/apimanager.py", line 115, in request
    response_content = json.loads(response.content)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
I've download my settings with `paconn download` and then executed with `paconn update --settings settings.json --debug`
**Expected behavior**
I expect that the API definition is updated and without errors.

**Environment summary**
```
paconn --version
0.0.13

Python (Darwin) 3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)]

Python location '/usr/local/opt/python/bin/python3.7'
```

macOS. paconn instaled using pip.

**Comment by nk-gears** [comment]
@diegobernardes I opened a ticket related to this #267 .This explains in detail

**Comment by dougelliott** [comment]
Closing as duplicate. Let's move conversation over to #267 to keep things organized.
