### ISSUE TITLE
paconn Error: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/PowerPlatformConnectors#993]
**Type of Connector**

- [ X ] certified 
- [ ] custom 
- [ ] independent publisher

*paconn*

**Error: the JSON object must be str, not 'bytes'**
When running this command:

`paconn create --api-prop ./apiProperties.json --api-def ./apiDefinition.swagger.json --icon ./icon.png`

We are receiving this output, which appears to be an unhandled exception in paconn:

```
c:\python35\lib\site-packages\azure\storage\blob\_encryption.py:13: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat.primitives.padding import PKCS7
Please select an environment:
 [1] Default Environment
Please enter a choice [Default choice(1)]:
Environment selected: Default Environment
the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\paconn\apimanager\apimanager.py", line 112, in request
    response.raise_for_status()
  File "c:\python35\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.powerapps.com/providers/Microsoft.PowerApps/objectIds/validateApiSwagger?api-version=2016-11-01

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\python35\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "c:\python35\lib\site-packages\knack\commands.py", line 131, in __call__
    return self.handler(*args, **kwargs)
  File "c:\python35\lib\site-packages\knack\commands.py", line 238, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\python35\lib\site-packages\paconn\commands\create.py", line 52, in create
    overwrite_settings=overwrite_settings)
  File "c:\python35\lib\site-packages\paconn\operations\upsert.py", line 117, in upsert
    enable_certification_rules=False)
  File "c:\python35\lib\site-packages\paconn\apimanager\powerappsrp.py", line 106, in validate_connector
    payload=payload)
  File "c:\python35\lib\site-packages\paconn\apimanager\apimanager.py", line 115, in request
    response_content = json.loads(response.content)
  File "c:\python35\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Is this a security bug?**
- [ ] yes
- [ X ] no

**What is the severity of this bug?**
- [ X ] severity 1: Connector is broken or there's a very serious issue
- [ ] severity 2: One or more important connector features are down
- [ ] severity 3: Minor issue

**To Reproduce**
See above

**Expected behavior**
Does not crash

**Environment summary**
Latest version of paconn CLI

**Comment by mamurshe** [comment]
Which version of paconn are you using? Can you please send me the assets?

**Comment by Cloudmersive** [comment]
@mamurshe We are using version 0.0.18

Can you provide an email address to send the files to?  Thank you

**Comment by nk-gears** [comment]
@Cloudmersive 

Take a look at this thread. This may help you.

 https://github.com/microsoft/PowerPlatformConnectors/issues/267

**Comment by ccpauto** [comment]
Duplicate of: https://github.com/microsoft/PowerPlatformConnectors/issues/267
